//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsCamera.h
//  @ Date : 1/18/2010
//  @ Author : 
//
//


#if !defined(_WSCAMERA_H)
#define _WSCAMERA_H

#include "WsVision.h"
#include "WsVisionTarget.h"
#include "Vision/ColorImage.h"
#include "Vision/AxisCamera.h"

class WsCamera : public WsVision
{
public:
    WsCamera(AxisCamera *a);
    virtual ~WsCamera();
    virtual void findCandidates(void );
    virtual bool isTargetFound(void );
    virtual double getTargetHeading(void );
    virtual int getNumCandidates(void );
    virtual bool getCandidateInfo(unsigned int idx, WsVisionTarget &target);
protected:
    AxisCamera *ap_camera;

    void FindCircularTargets(ColorImage *image);
};

#endif  //_WSCAMERA_H
