//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsDoubleSolenoid.h
//  @ Date : 2/11/2010
//  @ Author : 
//
//


#if !defined(_WSDOUBLESOLENOID_H)
#define _WSDOUBLESOLENOID_H

#include "WsOutput.h"
#include "Solenoid.h"

class WsDoubleSolenoid : public WsOutput {
public:
    typedef enum {
      kOnA, kOnB, kOff
    } DoubleSolenoidStateT;

    WsDoubleSolenoid(UINT32 aChannel, UINT32 bChannel);
    WsDoubleSolenoid(UINT32 aSlot, UINT32 aChannel, UINT32 bSlot, UINT32 bChannel);
    ~WsDoubleSolenoid();
    void Set(DoubleSolenoidStateT state);
    DoubleSolenoidStateT Get();
protected:
    Solenoid *aSolenoid;
    Solenoid *bSolenoid;
};

#endif  //_WSDOUBLESOLENOID_H
