//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsDoubleSolenoid.cpp
//  @ Date : 2/11/2010
//  @ Author : 
//
//


#include "WsDoubleSolenoid.h"

WsDoubleSolenoid::WsDoubleSolenoid(UINT32 aChannel, UINT32 bChannel)
    : WsOutput()
{
    aSolenoid = new Solenoid(aChannel);
    bSolenoid = new Solenoid(bChannel);
}

WsDoubleSolenoid::WsDoubleSolenoid(UINT32 aSlot, UINT32 aChannel,
                                   UINT32 bSlot, UINT32 bChannel)
    : WsOutput()
{
    aSolenoid = new Solenoid(aSlot, aChannel);
    bSolenoid = new Solenoid(bSlot, bChannel);
}

WsDoubleSolenoid::~WsDoubleSolenoid()
{
    delete aSolenoid;
    delete bSolenoid;
}

void WsDoubleSolenoid::Set(DoubleSolenoidStateT state)
{
    switch (state)
    {
        case kOnA:
            aSolenoid->Set(true);
            bSolenoid->Set(false);
            break;
        case kOnB:
            aSolenoid->Set(false);
            bSolenoid->Set(true);
            break;
        default:
            aSolenoid->Set(false);
            bSolenoid->Set(false);
    }
}

WsDoubleSolenoid::DoubleSolenoidStateT WsDoubleSolenoid::Get()
{
    if (aSolenoid->Get())
        return kOnA;
    if (bSolenoid->Get())
        return kOnB;
    return kOff;
}

