//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsDriveBaseCrabSingle.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSDRIVEBASECRABSINGLE_H)
#define _WSDRIVEBASECRABSINGLE_H

#include <stdio.h>
#include "WsDriveBaseTank.h"

class WsCrabController;

class WsDriveBaseCrabSingle : public WsDriveBaseTank
{
public:
    WsDriveBaseCrabSingle(WsSc* p_lf, WsSc* p_lb,
                          WsSc* p_rf, WsSc* p_rb,
                          WsCrabController* p_crabController);
    virtual ~WsDriveBaseCrabSingle();
    virtual void setCrabAngle(float angle);
    virtual void setManualSpeed(float speed);
    virtual void setVector(WsDriveVector* p_vector);
    virtual void useAlignPid(bool use);
protected:
    WsCrabController *ap_crabController;
    float a_crabAngle;
    float a_is_crabbed_thresh;
};

#endif  //_WSDRIVEBASECRABSINGLE_H
