//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsKickerRange.h
//  @ Date : 1/27/2010
//  @ Author : 
//
//


#if !defined(_WSKICKERRANGE_H)
#define _WSKICKERRANGE_H

class WsSolenoid;

class WsKickerRange {
public:
    typedef enum {
        KICKER_RANGE_NONE = 0,
        KICKER_RANGE_NEAR,
        KICKER_RANGE_FAR,
    } WsKickerRangeT;

    WsKickerRange(WsSolenoid* p_solenoid);
    ~WsKickerRange();

    void setRange(WsKickerRangeT range);
    WsKickerRange::WsKickerRangeT getRange(void );
    void resetState(void );
protected:
    WsSolenoid* ap_solenoid;
    WsKickerRangeT a_state;
    WsKickerRangeT a_defaultState;
};

#endif  //_WSKICKERRANGE_H
