//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsKickerLatch.h
//  @ Date : 1/27/2010
//  @ Author : 
//
//


#if !defined(_WSKICKERLATCH_H)
#define _WSKICKERLATCH_H

class WsSolenoid;

class WsKickerLatch {
public:
    typedef enum {
        KICKER_LATCH_NONE = 0,
        KICKER_LATCH_HOLD,
        KICKER_LATCH_RELEASE,
    } WsKickerLatchStateT;

    WsKickerLatch(WsSolenoid* p_solenoid);
    ~WsKickerLatch();
    void setState(WsKickerLatchStateT state);
    WsKickerLatchStateT getState(void );
    void resetState(void );
protected:
    WsSolenoid* ap_solenoid;
    WsKickerLatchStateT a_state;
    WsKickerLatchStateT a_defaultState;
};

#endif  //_WSKICKERLATCH_H
