//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsKickerTensioner.cpp
//  @ Date : 1/27/2010
//  @ Author : 
//
//

#include <stdio.h>

#include "WsKickerTensioner.h"
#include "WsSolenoid.h"

WsKickerTensioner::WsKickerTensioner(WsSolenoid* p_solenoid)
{
    ap_solenoid = p_solenoid;
    a_defaultState = KICKER_TENSION_UP;
    a_state = a_defaultState;
}

WsKickerTensioner::~WsKickerTensioner()
{

}

void WsKickerTensioner::setTension(WsKickerTensionT tension)
{
    if (ap_solenoid != NULL)
    {
        if (tension != KICKER_TENSION_NONE)
        {
            a_state = tension;
        }

        if (a_state == KICKER_TENSION_UP)
        {
            ap_solenoid->Set(false);
        }
        else if (a_state == KICKER_TENSION_DOWN)
        {
            ap_solenoid->Set(true);
        }
    }
}

WsKickerTensioner::WsKickerTensionT WsKickerTensioner::getTension(void )
{
    return a_state;
}

void WsKickerTensioner::resetState(void )
{
    setTension(a_defaultState);
}

