//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsKickerRange.cpp
//  @ Date : 1/27/2010
//  @ Author : 
//
//

#include <stdio.h>

#include "WsKickerRange.h"
#include "WsSolenoid.h"

WsKickerRange::WsKickerRange(WsSolenoid* p_solenoid)
{
    ap_solenoid = p_solenoid;
    a_defaultState = KICKER_RANGE_NEAR;
    a_state = a_defaultState;
}

WsKickerRange::~WsKickerRange()
{

}

void WsKickerRange::setRange(WsKickerRangeT range)
{
    if (ap_solenoid != NULL)
    {
        if (range != KICKER_RANGE_NONE)
        {
            a_state = range;
        }

        if (a_state == KICKER_RANGE_NEAR)
        {
            ap_solenoid->Set(false);
        }
        else if (a_state == KICKER_RANGE_FAR)
        {
            ap_solenoid->Set(true);
        }
    }
}

WsKickerRange::WsKickerRangeT WsKickerRange::getRange(void )
{
    return a_state;
}

void WsKickerRange::resetState(void )
{
    setRange(a_defaultState);
}

