//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsKickerLoft.cpp
//  @ Date : 1/27/2010
//  @ Author : 
//
//

#include <stdio.h>

#include "WsKickerLoft.h"
#include "WsSolenoid.h"

WsKickerLoft::WsKickerLoft(WsSolenoid* p_solenoid)
{
    ap_solenoid = p_solenoid;
    a_defaultState = KICKER_LOFT_HIGH;
    a_state = a_defaultState;
}

WsKickerLoft::~WsKickerLoft()
{

}

void WsKickerLoft::setLoft(WsKickerLoftT state)
{
    if (ap_solenoid != NULL)
    {
        if (state != KICKER_LOFT_NONE)
        {
            a_state = state;
        }

        if (a_state == KICKER_LOFT_HIGH)
        {
            ap_solenoid->Set(false);
        }
        else if (a_state == KICKER_LOFT_LOW)
        {
            ap_solenoid->Set(true);
        }
    }
}

WsKickerLoft::WsKickerLoftT WsKickerLoft::getLoft(void )
{
    return a_state;
}

void WsKickerLoft::resetState(void )
{
    setLoft(a_defaultState);
}

