//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2010
//  @ File Name : WsMotorManager.cpp
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#include "WsMotorManager.h"
#include "WsOutput.h"

WsMotorManager::WsMotorManager()
{
    UINT8 i;
    for (i = 0; i < MAX_OUTPUTS; i++)
    {
        a_outputs[i] = NULL;
    }
    a_index = 0;

}

WsMotorManager::~WsMotorManager()
{
}

void WsMotorManager::addOutput(WsOutput* p_output)
{
    if (a_index < MAX_OUTPUTS)
    {
        a_outputs[a_index] = p_output;
        a_index++;
    }
    else
    {
        printf("Output array full\n");
    }
}

void WsMotorManager::enableDebug(bool debug)
{
    UINT8 i;
    for (i = 0; i < a_index; i++)
    {
        a_outputs[i]->setDebug(debug);
    }

}

void WsMotorManager::enableMotors(bool enable)
{
    UINT8 i;
    for (i = 0; i < a_index; i++)
    {
        a_outputs[i]->setEnabled(enable);
    }

}

