//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsMotorManager.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSMOTORMANAGER_H)
#define _WSMOTORMANAGER_H

#include <stdio.h>

#define MAX_MOTORS 14
#define MAX_RELAYS 8
#define MAX_OUTPUTS ((MAX_MOTORS) + (MAX_RELAYS))

class WsOutput;

class WsMotorManager
{
public:
    WsMotorManager();
    virtual ~WsMotorManager();
    void addOutput(WsOutput* p_output);
    void enableDebug(bool debug);
    void enableMotors(bool enable);
protected:
    WsOutput* a_outputs[MAX_OUTPUTS];
    UINT8 a_index;
};

#endif  //_WSMOTORMANAGER_H
