//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WsOutput.h
//  @ Date : 1/24/2009
//  @ Author : 
//
//


#if !defined(_WSOUTPUT_H)
#define _WSOUTPUT_H

#include <stdio.h>

class WsOutput
{
public:
    WsOutput();
    ~WsOutput();
    void setEnabled(bool enable);
    void setDebug(bool debug);
protected:
    bool a_enabled;
    bool a_debug;
};

#endif  //_WSOUTPUT_H
