//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsPidParams.h
//  @ Date : 1/26/2010
//  @ Author : 
//
//


#if !defined(_WSPIDPARAMS_H)
#define _WSPIDPARAMS_H

#include <stdio.h>

class WsPidParams
{
public:
    float a_p;
    float a_i;
    float a_d;
    int   a_eps;
};

#endif  //_WSPIDPARAMS_H
