//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WsPot.h
//  @ Date : 1/21/2009
//  @ Author : 
//
//


#if !defined(_WSPOT_H)
#define _WSPOT_H

#include <stdio.h>
#include "AnalogChannel.h"

class WsPot : public AnalogChannel
{
public:
    WsPot(UINT32 slot, UINT32 channel);
    virtual ~WsPot();
};

#endif  //_WSPOT_H
