//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2010
//  @ File Name : WsPot.cpp
//  @ Date : 1/21/2009
//  @ Author : 
//
//


#include "WsPot.h"

WsPot::WsPot(UINT32 slot, UINT32 channel):
    AnalogChannel(slot, channel)
{
    // Take a break :)
}

WsPot::~WsPot()
{
}
