//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WsRelay.h
//  @ Date : 1/24/2009
//  @ Author : 
//
//


#if !defined(_WSRELAY_H)
#define _WSRELAY_H

#include <stdio.h>
#include "WsOutput.h"
#include "Relay.h"

class WsRelay : public WsOutput
{
public:
    WsRelay(UINT32 channel);
    WsRelay(UINT32 slot, UINT32 channel);
    virtual ~WsRelay();
    void Set(Relay::Value value);
protected:
    Relay *ap_relay;
};

#endif  //_WSRELAY_H
