//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2010
//  @ File Name : WsRelay.cpp
//  @ Date : 1/24/2009
//  @ Author : 
//
//


#include "WsRelay.h"
#include "WsOutput.h"
#include "Relay.h"

WsRelay::WsRelay(UINT32 channel)
    : WsOutput()
{
    ap_relay = new Relay(channel);
}

WsRelay::WsRelay(UINT32 slot, UINT32 channel)
    : WsOutput()
{
    ap_relay = new Relay(slot, channel);
}

WsRelay::~WsRelay()
{
    delete ap_relay;
}

void WsRelay::Set(Relay::Value value)
{
    if (a_enabled == true)
    {
        ap_relay->Set(value);
    }
    else
    {
        ap_relay->Set(Relay::kOff);
    }

}

