//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsSc.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSSC_H)
#define _WSSC_H

#include <stdio.h>
#include "WsOutput.h"

class SpeedController;

class WsSc : public WsOutput
{
public:
    typedef enum {
        WS_SC_VICTOR,
        WS_SC_JAGUAR,
    } WsScT;

    WsSc(WsScT type, UINT32 channel);
    WsSc(WsScT type, UINT32 slot, UINT32 channel);
    virtual ~WsSc();
    virtual float Get(void);
    virtual void Set(float speed);
    bool a_debug;
protected:
    SpeedController *ap_sc;
};

#endif  //_WSSC_H
