//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsShmCamera.h
//  @ Date : 1/18/2010
//  @ Author : 
//
//


#if !defined(_WSSHMCAMERA_H)
#define _WSSHMCAMERA_H

#include "WsVision.h"
#include "WsVisionTarget.h"

class WsShmCamera : public WsVision
{
public:
    WsShmCamera();
    virtual ~WsShmCamera();
    virtual void findCandidates(void );
    virtual bool isTargetFound(void );
    virtual double getTargetHeading(void );
    virtual int getNumCandidates(void );
    virtual bool getCandidateInfo(unsigned int idx, WsVisionTarget &target);
    virtual void getAllCandidates(std::vector<WsVisionTarget>& targets);
protected:
    bool targetFound;
    double targetHeading;
};

#endif  //_WSSHMCAMERA_H
