//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsSolenoid.cpp
//  @ Date : 1/27/2010
//  @ Author : 
//
//


#include "WsSolenoid.h"
#include "Solenoid.h"

WsSolenoid::WsSolenoid(UINT32 channel)
    : WsOutput()
{
    ap_solenoid = new Solenoid(channel);
}

WsSolenoid::WsSolenoid(UINT32 slot, UINT32 channel)
    : WsOutput()
{
    ap_solenoid = new Solenoid(slot, channel);
}

WsSolenoid::~WsSolenoid()
{
    delete ap_solenoid;
}

void WsSolenoid::Set(bool on)
{
    if (ap_solenoid != NULL)
    {
        if (a_enabled == true)
        {
            ap_solenoid->Set(on);
        }
        else
        {
            ap_solenoid->Set(false);
        }
    }
}

