//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsTowerFingers.h
//  @ Date : 2/15/2010
//  @ Author : 
//
//


#if !defined(_WSTOWERFINGERS_H)
#define _WSTOWERFINGERS_H

#include <stdio.h>

class WsDoubleSolenoid;

class WsTowerFingers
{
public:
    typedef enum
    {
        TOWER_FINGER_STATE_NONE,
        TOWER_FINGER_STATE_IN,
        TOWER_FINGER_STATE_OUT,
    } WsTowerFingerStateT;

    WsTowerFingers(WsDoubleSolenoid* p_fingerDeploy);
    ~WsTowerFingers();

    void setState(WsTowerFingerStateT state);
    WsTowerFingerStateT getState(void );

protected:
    WsDoubleSolenoid* ap_fingerDeploy;
    WsTowerFingerStateT a_fingerState;
};

#endif  //_WSTOWERFINGERS_H
