//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsTowerAlign.h
//  @ Date : 2/15/2010
//  @ Author : 
//
//


#if !defined(_WSTOWERALIGN_H)
#define _WSTOWERALIGN_H

#include <stdio.h>

class Servo;

class WsTowerAlign
{
public:

    typedef enum
    {
        TOWER_ALIGN_STATE_NONE,
        TOWER_ALIGN_STATE_IN,
        TOWER_ALIGN_STATE_OUT,
    } WsTowerAlignStateT;

    float a_alignServoIn;
    float a_alignServoOut;

    WsTowerAlign(Servo* p_AlignDeploy);
    ~WsTowerAlign();
    void setState(WsTowerAlignStateT state);
    WsTowerAlign::WsTowerAlignStateT getState(void );

    WsTowerAlignStateT a_alignState;
protected:
    Servo* ap_alignDeploy;
};

#endif  //_WSTOWERALIGN_H
