//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsTowerAlign.cpp
//  @ Date : 2/15/2010
//  @ Author : 
//
//


#include "WsTowerAlign.h"
#include "Servo.h"

WsTowerAlign::WsTowerAlign(Servo* p_AlignDeploy)
{
    ap_alignDeploy = p_AlignDeploy;
    a_alignServoIn = .4;
    a_alignServoOut = 0;
    //a_alignServoIn = .55; // CAMERA SERVO POS
}

WsTowerAlign::~WsTowerAlign()
{

}

void WsTowerAlign::setState(WsTowerAlignStateT state)
{
    float towerAlignValue = a_alignServoIn;
    a_alignState = state;
    if(ap_alignDeploy != NULL)
    {
        if(a_alignState == TOWER_ALIGN_STATE_OUT)
        {
            towerAlignValue = a_alignServoOut;
        }
        else
        {
            towerAlignValue = a_alignServoIn;
        }

        ap_alignDeploy->Set(towerAlignValue);

        //printf("ALIGN: %f\n",  towerAlignValue);
    }

}

WsTowerAlign::WsTowerAlignStateT WsTowerAlign::getState(void )
{
    return a_alignState;
}

