//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsTunableController.cpp
//  @ Date : 1/26/2010
//  @ Author : 
//
//


#include "WsTunableController.h"
#include "WsPid.h"

WsPid* WsTunableController::getPid(void )
{
    return NULL;
}

void WsTunableController::runStepTest(float input, UINT32& currentVal, float& speed)
{
    // Do nothing
    currentVal = 0;
    speed = 0;
}

void WsTunableController::endStepTest(void)
{
    // Do nothing
}

void WsTunableController::runPidTest(float input)
{
}
