//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsVision.h
//  @ Date : 1/18/2010
//  @ Author : 
//
//


#if !defined(_WSVISION_H)
#define _WSVISION_H

#include "WsVisionTarget.h"
#include <vector>

class WsVision
{
public:
    WsVision();
    virtual ~WsVision();
    virtual void clearTargets(void );
    virtual void findCandidates(void );
    virtual bool isTargetFound(void );
    virtual double getTargetHeading(void );
    virtual int getNumCandidates(void );
    virtual bool getCandidateInfo(int idx, WsVisionTarget &target);
protected:
    std::vector<WsVisionTarget> a_targets;
};

#endif  //_WSVISION_H
