//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsVisionTarget.h
//  @ Date : 1/18/2010
//  @ Author : 
//
//


#if !defined(_WSTARGET_H)
#define _WSTARGET_H


class WsVisionTarget
{
public:
    double a_majorRadius;
    double a_minorRadius;
    double a_rawScore;
    double a_xPos;
    double a_yPos;
    double a_score;
    double a_rotation;
    double a_xMax;
    bool   a_bothFound;

    WsVisionTarget();
    WsVisionTarget(double majorRadius, double minorRadius, double rawScore,
                   double xPos, double yPos, double score, double rotation,
                   double xMax, bool bothFound);
    ~WsVisionTarget();
    double getHorizontalAngle();
    void copyFrom(WsVisionTarget *t);
    void print();
};

#endif  //_WSTARGET_H
