//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsVision.cpp
//  @ Date : 1/18/2010
//  @ Author : 
//
//


#include "WsVision.h"
using namespace std;

WsVision::WsVision()
{

}

WsVision::~WsVision()
{

}

void WsVision::clearTargets(void )
{
  a_targets.clear();
}

void WsVision::findCandidates(void )
{

}

bool WsVision::isTargetFound(void )
{
  return false;
}

double WsVision::getTargetHeading(void )
{
  return 0;
}

int WsVision::getNumCandidates(void )
{
  return 0;
}

bool WsVision::getCandidateInfo(int idx, WsVisionTarget &target)
{
  return false;
}

